global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          alias: 'Prometheus Server'

  - job_name: 'node_exporter_api'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          alias: 'LX-API01'
          server: 'API Server'

  - job_name: 'node_exporter_db'
    static_configs:
      - targets: ['db.corpkvb.local:9100']
        labels:
          alias: 'LX-DB01'
          server: 'Database Server'